name: 'Branch Merge'
description: 'Automatically merge branches.'
branding:
  icon: 'git-merge'
  color: 'orange'
inputs:
  source_branch:
    description: 'Name of the source branch'
    required: true
  target_branch:
    description: 'Name of the target branch'
    required: true
  allow_ff:
    description: 'Allow fast forward merge'
    required: false
    default: false
  ff_only:
    description: 'Refuse to perform a non fast forward merge (requires allow_ff=true)'
    required: false
    default: false
  user_name:
    description: 'User name for git commits'
    required: false
    default: 'github-actions[bot]'
  user_email:
    description: 'User email for git commits'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  push_token:
    description: 'Environment variable containing the token to use for push'
    required: false
    default: 'GITHUB_TOKEN'
  commit_message:
    description: 'Commit message for merge commit'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
